const projects = [
  { folder: "01_joana-s",
    title: "Joana S",
    vimeo: ["982471791"], ratio: ["16/9"],
    poster: "00_poster_Joana.gif",
    photos: ["1 joana.jpg","2 joana.jpg","3 joana.jpg","4 joana.jpg","5 joana.jpg","6 joana.jpg","7 joana.jpg","8 joana.jpg","9 joana.jpg","10 joana.jpg","11 joana.jpg"] },

  { folder: "02_miriam-quevedo-gold-oil",
    title: "Miriam Quevedo Gold Oil",
    vimeo: ["1187282980"], ratio: ["9/16"],
    poster: "00_poster_mq gold.gif",
    photos: [] },

  { folder: "03_jules-jenn",
    title: "Jules & Jenn",
    vimeo: [], ratio: [],
    poster: "00_poster_jules.jpg",
    photos: ["1 julesandjenn.jpg","2 julesandjenn.jpg","3 julesandjenn.jpg","4 julesandjenn.jpg"] },

  { folder: "04_skeyndor-gold",
    title: "Skeyndor Gold",
    vimeo: ["846305881"], ratio: ["16/9"],
    poster: "00_poster_ SPA Senses-low.gif",
    photos: [] },

  { folder: "05_miriam-quevedo-ondas",
    title: "Miriam Quevedo Ondas",
    vimeo: ["581168478", "581168017"], ratio: ["16/9","16/9"],
    poster: "00_poster_mq ondas.gif",
    photos: [] },

  { folder: "06_sara-carmona-ft-sprinter",
    title: "Sara Carmona ft. Sprinter",
    vimeo: ["1061276421"], ratio: ["9/16"],
    poster: "00_poster_sara.png",
    photos: ["1 sara carmona.png","2 sara carmona.jpg","3 sara carmona.jpg","4 sara carmona.jpg","5 sara carmona.jpg"] },

  { folder: "07_aitana-fragrance",
    title: "Aitana Fragrance",
    vimeo: ["1187276093"], ratio: ["9/16"],
    poster: "00_poster_aitana.gif",
    photos: [] },

  { folder: "08_vallformosa-celebrate",
    title: "Vallformosa Celebrate",
    vimeo: ["1187264942"], ratio: ["16/9"],
    poster: "00_poster_vallformosa.png",
    photos: ["02 vallformosa.jpg","03 vallformosa.jpeg","4 vallformosa.jpg","5 vallformosa.jpg","6 vallformosa.jpg","8 vallformosa.jpg","9 vallformosa.jpg","10 vallformosa.jpg","11 vallformosa.jpg","13 vallformosa.jpg","14 vallformosa.jpg","15 vallformosa.jpg"] },

  { folder: "09_dina-s",
    title: "Dina S",
    vimeo: [], ratio: [],
    poster: "00_poster_dina.jpeg",
    photos: ["1 dina.jpeg","2 dina.jpeg","3 dina.jpeg","4 dina.jpeg","5 dina.jpeg","6 dina.jpg","7 dina.jpg","8 dina.jpg","10 dina.jpg","11 dina.jpg","12 dina.jpg","13 dina.jpg"] },

  { folder: "10_skeyndor-white",
    title: "Skeyndor White",
    vimeo: ["581130636"], ratio: ["16/9"],
    poster: "00_poster_SKEYNDOR_ProBiome.gif",
    photos: [] },

  { folder: "11_carlota-s",
    title: "Carlota S",
    vimeo: ["1061270393"], ratio: ["9/16"],
    poster: "00_poster_carlota.png",
    photos: ["1 carlota.jpg","2 carlota.jpg","3 carlota.jpg"] },

  { folder: "12_bicentury-take-away",
    title: "Bicentury Take Away",
    vimeo: [], ratio: [],
    poster: "00_poster.jpg",
    photos: ["1 bicentury takeaway.jpeg","2 bicentury takeaway.jpeg","3 bicentury takeaway.jpg","4 bicentury takeaway.jpg","5 bicentury takeaway.jpg","6 bicentury takeaway.webp"] },

  { folder: "13_nescafe-celebramosalgo",
    title: "Nescafé #celebramosalgo",
    vimeo: ["282174445"], ratio: ["16/9"],
    poster: "00_poster_nescafe.gif",
    photos: [] },

  { folder: "14_el-corte-ingles-por-tu-verano",
    title: "El Corte Inglés Por Tu Verano",
    vimeo: ["1187277351"], ratio: ["1/1"],
    poster: "00_poster_eci.jpg",
    photos: [] },

  { folder: "15_double-agent-summer",
    title: "Double Agent Summer",
    vimeo: ["277430359"], ratio: ["16/9"],
    poster: "00_poster_ Double Agent Summer.jpg",
    photos: [] },

  { folder: "16_bershka",
    title: "Bershka",
    vimeo: ["1187280376"], ratio: ["9/16"],
    poster: "00_poster_bershka.gif",
    photos: [] },

  { folder: "17_miriam-quevedo-rizos",
    title: "Miriam Quevedo Rizos",
    vimeo: ["581168530","581167780"], ratio: ["16/9","16/9"],
    poster: "00_poster_mq rizos.gif",
    photos: [] },

  { folder: "18_miriam-quevedo-foam-solution",
    title: "Miriam Quevedo Foam Solution",
    vimeo: ["581188389","493308244"], ratio: ["16/9","16/9"],
    poster: "00_poster_mq_foam.gif",
    photos: [] },

  { folder: "19_flower-romance",
    title: "Flower Romance",
    vimeo: ["232854451"], ratio: ["16/9"],
    poster: "00_poster_flower copia.gif",
    photos: [] },

  { folder: "20_candince-s",
    title: "Candince S",
    vimeo: [], ratio: [],
    poster: "00_poster_candince.png",
    photos: ["1 candince.jpg","2 candince.jpeg","3 candince.jpeg","4 candince.jpg","5 candince.jpg","6 candince.jpg"] },

  { folder: "21_rita-studio",
    title: "Rita Studio",
    vimeo: [], ratio: [],
    poster: "00_poster_rita.jpeg",
    photos: ["1 rita.jpeg","2 rita.jpg","3 rita.jpg","4 rita.jpeg"] },

  { folder: "22_nastya-s",
    title: "Nastya S",
    vimeo: ["337256738"], ratio: ["16/9"],
    poster: "00_poster_nastya.gif",
    photos: [] },

  { folder: "23_kaleos-new-in",
    title: "Kaleos New In",
    vimeo: ["387397787"], ratio: ["16/9"],
    poster: "00_poster_kaleos.gif",
    photos: [] },

  { folder: "24_yana-s",
    title: "Yana S",
    vimeo: ["337256661"], ratio: ["16/9"],
    poster: "00_poster_yana.gif",
    photos: [] },
];
