const projects = [
  { folder: "01_joana-s",                        title: "Joana S",                          vimeo: "982471791",  poster: "00_poster_joana.png", photos: ["1_joana.jpeg","2_joana.jpeg","3_joana.jpeg","4_joana.jpeg","5_joana.jpeg","6_joana.jpeg","7_joana.jpg","8_joana.jpg","9_joana.jpg","10_joana.jpg","11_joana.jpg","12_joana.jpeg"] },
  { folder: "02_miriam-quevedo-gold-oil",        title: "Miriam Quevedo Gold Oil",          vimeo: "581168478",  photos: [] },
  { folder: "03_jules-jenn",                     title: "Jules & Jenn",                     vimeo: "",           photos: [] },
  { folder: "04_skeyndor-gold",                  title: "Skeyndor Gold",                    vimeo: "846305881",  photos: [] },
  { folder: "05_miriam-quevedo-ondas",           title: "Miriam Quevedo Ondas",             vimeo: "",           photos: [] },
  { folder: "06_sara-carmona-ft-sprinter",       title: "Sara Carmona ft. Sprinter",        vimeo: "",           photos: [] },
  { folder: "07_aitana-fragrance",               title: "Aitana Fragrance",                 vimeo: "",           photos: [] },
  { folder: "08_vallformosa-summer",             title: "Vallformosa Summer",               vimeo: "",           photos: [] },
  { folder: "09_dina-s",                         title: "Dina S",                           vimeo: "",           photos: [] },
  { folder: "10_skeyndor-white",                 title: "Skeyndor White",                   vimeo: "",           photos: [] },
  { folder: "11_carlota-s",                      title: "Carlota S",                        vimeo: "",           photos: [] },
  { folder: "12_bicentury-take-away",            title: "Bicentury Take Away",              vimeo: "",           photos: [] },
  { folder: "13_nescafe-celebramosalgo",         title: "Nescafé #celebramosalgo",          vimeo: "282174445",  photos: [] },
  { folder: "14_el-corte-ingles-por-tu-verano",  title: "El Corte Inglés Por Tu Verano",    vimeo: "",           photos: [] },
  { folder: "15_double-agent-summer",            title: "Double Agent Summer",              vimeo: "277430359",  photos: [] },
  { folder: "16_bershka",                        title: "Bershka",                          vimeo: "",           photos: [] },
  { folder: "17_miriam-quevedo-rizos",           title: "Miriam Quevedo Rizos",             vimeo: "581168530",  photos: [] },
  { folder: "18_victorio-lucchino-fragrance",    title: "Victorio Lucchino Fragrance",      vimeo: "292949639",  photos: [] },
  { folder: "19_flower-romance",                 title: "Flower Romance",                   vimeo: "232854451",  photos: [] },
  { folder: "20_candince-s",                     title: "Candince S",                       vimeo: "",           photos: [] },
  { folder: "21_rita-studio",                    title: "Rita Studio",                      vimeo: "",           photos: [] },
  { folder: "22_miriam-quevedo-foam-solution",   title: "Miriam Quevedo Foam Solution",     vimeo: "",           photos: [] },
  { folder: "23_ramona-s",                       title: "Ramona S",                         vimeo: "",           photos: [] },
  { folder: "24_nastya-s",                       title: "Nastya S",                         vimeo: "337256738",  photos: [] },
  { folder: "25_kaleos-new-in",                  title: "Kaleos New In",                    vimeo: "387397787",  photos: [] },
  { folder: "26_yana-s",                         title: "Yana S",                           vimeo: "337256661",  photos: [] },
  { folder: "27_amaya-s",                        title: "Amaya S",                          vimeo: "",           photos: [] },
];
